 env: "local" #local, dev, prod
 http_server:
  address: "0.0.0.0:8080"
  timeout: "4s"
  idle_timeout: "60s"
  user: "admin"
 database:
  host: "db"
  port: 5432
  user: "postgres"
  name: "shop"
 jwt:
  token_ttl: 60
 migrations:
  path: "./migrations"